# Generated by Django 6.0.6 on 2026-06-06 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutZoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('email', models.EmailField(max_length=254, verbose_name='Емейл')),
                ('phone', models.CharField(help_text='Введите ровно 11 цифр (например: 79123456789)', max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Телефон должен содержать ровно 11 цифр без пробелов и знаков', regex='^\\d{11}$')], verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'О зоопарке',
                'verbose_name_plural': 'О зоопарке',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together=set(),
        ),
    ]
