# Generated by Django 6.0.6 on 2026-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
