# Generated by Django 6.0.6 on 2026-06-05 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramsettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramsettings',
            name='logo',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
