# Generated by Django 6.0.6 on 2026-06-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_aboutzoom_photo_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutZoom',
            new_name='AboutZoo',
        ),
    ]
