# Generated by Django 6.0.6 on 2026-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_rename_aboutzoom_aboutzoo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name': 'Опции', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
