# Generated by Django 6.0.6 on 2026-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_telegramsettings_options_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
