# Generated by Django 6.0.6 on 2026-06-06 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_alter_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
    ]
