# Generated by Django 6.0.6 on 2026-06-06 17:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_photo_archived_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutzoo',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Цена взрослого билета'),
        ),
        migrations.AddField(
            model_name='aboutzoo',
            name='reduced_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Цена льготного билета'),
        ),
    ]
