# Generated by Django 6.0.6 on 2026-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_aboutzoo_adult_price_aboutzoo_reduced_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutzoo',
            name='advantages',
            field=models.TextField(default='', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='aboutzoo',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
