# Generated by Django 6.0.6 on 2026-06-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_aboutzoo_advantages_alter_aboutzoo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Программа опеки',
                'verbose_name_plural': 'Программа опеки',
            },
        ),
    ]
