# Generated by Django 6.0.6 on 2026-06-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_guardianprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Емодзи'),
        ),
    ]
