# Generated by Django 6.0.6 on 2026-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_animal_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('rating', models.IntegerField(choices=[(5, '⭐ Отлично'), (4, '👍 Хорошо'), (3, '😐 Нормально'), (2, '😕 Плохо'), (1, '👎 Ужасно')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
