# Generated by Django 6.0.6 on 2026-06-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('quiz_result', models.TextField(default='', verbose_name='Результаты викторины')),
                ('message', models.TextField(default='', verbose_name='Сообщение от пользователя')),
                ('flag', models.BooleanField(default=False, verbose_name='Флаг')),
                ('handled', models.BooleanField(default=False, verbose_name='Отработано')),
            ],
            options={
                'verbose_name': 'Потенциальный опекун',
                'verbose_name_plural': 'Потенциальные опекуны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='flag',
            field=models.BooleanField(default=False, verbose_name='Флаг'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='handled',
            field=models.BooleanField(default=False, verbose_name='Отработано'),
        ),
    ]
