# Generated by Django 6.0.6 on 2026-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_potentialguardian_feedback_flag_feedback_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='bot_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
